### ISSUE TITLE
Copy/Paste does not work between external programs and ImGUI application

### ISSUE THREAD

**Issue by christopherdumas** [swistakm/pyimgui#115] opened 2019-04-19 21:27 UTC
Hi, so I've set up a fairly large (at this point) ImGUI application based mostly around the example setup using SDL2 (https://github.com/swistakm/pyimgui/blob/master/doc/examples/integrations_pysdl2.py). I've noticed that although the clipboard appears to work within the ImGUI application (copying from one text box to another, for instance), I can't paste anything copied from outside of it, nor copy something from inside to the outside. I have no idea why this is happening, nor how to fix it. I'd be very grateful if someone could help me out. If you want to see my code, it's at https://github.com/christopherdumas/atomicdatabase.

**Comment by traverseda** [comment] 2019-08-25 10:19
So as near as I can tell imgui has its own clipboard management system. As near as I can tell pyimgui doesn't expose those calls right now.

Once pyimgui does, you could presumable call "imgui.get_clipboard_text()" to get the current imgui clipboard, and send it to the host operating system. Of course you could also do the reverse.

**Comment by DGriffin91** [comment] 2020-02-12 04:14
It appears that GetClipboardText() gets the host os clipboard not the imgui one. 

I made a build of pyimgui that included GetClipboardText() and SetClipboardText() and they seem to correctly manipulate the os clipboard, however I wasn't able to use them to make pasting into fields work. 

Something else must be a factor. I'm hoping to be able to figure this out as this is one of the main reasons I haven't been able to adopt pyimgui for various projects.

**Comment by DGriffin91** [comment] 2020-02-12 10:13
I just tested this with the SDL2, pygame, glfw, and pyglet integrations. With SDL2, pygame, and glfw the copy/paste was actually working as expected on my computer (windows 10). However, it was not working with pyglet (the integration I was previously trying to use). I took a look at the `integrations_glfw.py` vs `integrations_pyglet.py` and neither appear to have anything directly related to the clipboard.

**Comment by scotty007** [comment] 2020-03-17 21:10
Actually this is not a bug. ImGui supports the Windows system clipboard out of the box. And some of the example CPP(!) integrations use the `ImGuiIO::GetClipboardTextFn` and `ImGuiIO::SetClipboardTextFn` callbacks to add system clipboard support as well (e.g. GLFW). Everything else uses an internal ImGui clipboard.
#144 exposes those callbacks to Python and enables the system clipboard for GLFW.

**Comment by swistakm** [comment] 2020-07-20 12:15
Partial support (glfw and pysdl) for clipboard was merged through #105 and missing support for other integrations got their own issues assigned (see: #160, #161).

 That's why I'm closing this one in favour of #160 and #161..

**Closed by swistakm** 2020-07-20 12:15 UTC
Labels: bug

**Comment by swistakm** [comment] 2020-07-20 18:24
Feature released in 1.2.0
